config/routes.rb
gem 'grape'

Rails.application.routes.draw do
  mount Api::TunesApi => '/api'

  get "albums/index"

  get "ranking/index"
  get "ranking/latest_played"

  root :to => "welcome#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'users', :to => 'users#index', :as => :user_root

  resources :users do
    get :list , :on => :collection
    resources :tunes do
      resources :comments
      resources :progresses
      get :all , :on => :collection
      post :get_tunes_list , :on => :collection
      post :update_progress , :on => :collection
      get :load_tune_list, :on => :collection
      get :load_tune, :on => :collection
    end

    resources :albums do
      get :load_album_list, :on => :collection
    end

    resources :tunings do
      get :load_tuning_list, :on => :collection
    end
  end


  resources :comments do
    get :load_comment_list, :on => :collection
    resources :replies, :only => %w[create destroy]
  end

  resources :recordings
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :comment, :touch => true
  belongs_to :user

  validates :text, :presence => true
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def create
    comment = Comment.find(params[:comment_id])
    user = current_user

    new_reply = Reply.new(reply_params)
    new_reply.user = user
    new_reply.comment = comment
    unless new_reply.save
      render :nothing => true
      return
    end

    if request.smart_phone?
      render :json => {
        id: new_reply.id,
        text: new_reply.text,
        updated_at: new_reply.updated_at,
        user: new_reply.user
      }
    else
      render :json => {
        id: new_reply.id,
        html: render_to_string(:partial => "replies/reply_body", :locals => { :c => comment, :r => new_reply })
      }
    end

    EM::defer do
      ActiveRecord::Base.connection_pool.with_connection do
        begin
          send_mail_to_comment_owner(comment, new_reply)
          send_mail_to_comment_other(comment, new_reply)
        rescue => e
          logger.error e.class.name
          logger.error e.message
        end
      end
    end
  end

  def destroy
    Reply.find(params[:id]).destroy
    if request.smart_phone?
      comment = Comment.find(params[:comment_id])

      render :json => {
        id: comment.id,
        reply_latest_date: comment.updated_at.strftime("%m/%d"),
        count: comment.replies.count
      },
      :callback => 'removeReply'
    else
      @reply_id = params[:id] # destroy.js.erb で用いる
    end
  end

  private
  def send_mail_to_comment_owner(comment, reply)
    return if (!comment.user.notify and !comment.user.all_notify)
    return if comment.user == reply.user
    CommentMailer.to_owner(comment.user, comment, reply).deliver
  end

  def send_mail_to_comment_other(comment, reply)
    send_users = User.all.select{|u| u.all_notify}
    comment.replies.map{|r| r.user }.each{|u|
      next if !u.notify
      send_users << u
    }

    send_users.uniq.each{|u|
      next if u == reply.user
      next if u == comment.user
      sleep 10
      CommentMailer.to_other(u, comment, reply).deliver
    }
  end

  def reply_params
    params.require(:reply).permit(
      :text
    )
  end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_reply_body.html.erb
            <div id="reply_<%= r.id %>">
              <dl>
                <dt>
                  <%= r.created_at.strftime("%Y/%m/%d %H:%M") %>
                  <div class="comment-name">
                    <%= link_to r.user.default_name, user_tunes_path(r.user) %>
                    <%= icon_img(r.user) %>
                  </div>
                </dt>
                <dd>
                  <div class="comment-text" style="word-break:break-all;"><%= auto_link( simple_format(r.text)) %></div>
                  <% if r.user == current_user %>
                  <div class="comment-destroy">
                    <%= link_to 'x', comment_reply_path(c,r), :method => :delete,:remote => true, :confirm => "本当に削除しますか？" %>
                  </div>
                  <% end %>
                  <br>
                </dd>
              </dl>
            </div>
 

app/views/replies/destroy.js.erb
$('#reply_<%= @reply_id %>').fadeOut();