config/routes.rb
gem 'grape'

Rails.application.routes.draw do
  mount Api::TunesApi => '/api'

  get "albums/index"

  get "ranking/index"
  get "ranking/latest_played"

  root :to => "welcome#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'users', :to => 'users#index', :as => :user_root

  resources :users do
    get :list , :on => :collection
    resources :tunes do
      resources :comments
      resources :progresses
      get :all , :on => :collection
      post :get_tunes_list , :on => :collection
      post :update_progress , :on => :collection
      get :load_tune_list, :on => :collection
      get :load_tune, :on => :collection
    end

    resources :albums do
      get :load_album_list, :on => :collection
    end

    resources :tunings do
      get :load_tuning_list, :on => :collection
    end
  end


  resources :comments do
    get :load_comment_list, :on => :collection
    resources :replies, :only => %w[create destroy]
  end

  resources :recordings
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :tune
  belongs_to :user
  has_many :replies

  validates :text, :presence => true

  scope :by_tune, lambda {|tune|
    where(:tune_id => tune.id).order("updated_at DESC")
  }

  scope :latest, lambda {
    order("updated_at DESC").limit(20)
  }

  scope :other_by, lambda {|user, limit = 20|
    where("user_id != ?", user.id).order("updated_at DESC").limit(limit)
  }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    tune = Tune.find(params[:tune_id])

    @comment = @user.comments.build(comment_params)
    @comment.tune = tune
    unless @comment.save
      render :nothing => true
      return
    end

    if request.smart_phone?
      render :json => {
        comment: @comment,
        tune: tune,
        user: @user,
        replies: []
      }
    else
      render :json => {
        id: @comment.id,
        html: render_to_string(:partial => "comments/comment_body", :locals => { :c => @comment })
      }
    end
    EM::defer do
      ActiveRecord::Base.connection_pool.with_connection do
        begin
          send_mail_to_other(@comment)
        rescue => e
          logger.error e.class.name
          logger.error e.message
        end
      end
    end
  end

  def destroy
    @comment_id = params[:id] # destroy.js.erb で使う
    Comment.find(@comment_id).destroy
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def load_comment_list
    @comments = Comment.order("updated_at DESC").limit(30)

    lists = render_to_string :partial => 'comment_list_smart_phone'
    render :json => { lists: lists },
           :callback => 'showCommentList'
  end

  private
  def send_mail_to_other(comment)
    send_users = User.all.select{|u| u.all_notify}
    send_users.each{|u|
      next if u == comment.user
      sleep 10
      CommentMailer.to_other_with_comment(u, comment).deliver
    }
  end

  def comment_params
    params.require(:comment).permit(
      :text
    )
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment_body.html.erb
<div id="comment_<%= c.id %>">
  <dl>
    <dt>
      <div class="comment-date">
        <%= link_to c.created_at.strftime("%Y/%m/%d %H:%M"), comment_path(c.id) %>
      </div>
      <div style="float: right">
        <%= link_to reply_count_label(c), comment_path(c.id) %>
      </div>
    </dt>
    <br>
    <dd>
      <div class="comment-text" style="word-break:break-all;">
        <%= vrp_player_show( auto_link( simple_format(c.text))) %>
      </div>
      <% if c.user == current_user %>
      <div class="comment-destroy">
        <%= link_to c.user.default_name, user_tunes_path(c.user) %>
        <%= icon_img(c.user) %>
        <%= link_to 'x', user_tune_comment_path(c.user,c.tune,c), :method => :delete,:remote => true, :confirm => "本当に削除しますか？" %>
      </div>
      <% else %>
      <div style="float: right;" class="comment-name">
        by <%= link_to c.user.default_name, user_tunes_path(c.user) %>
        <%= icon_img(c.user) %>
      </div>
      <% end %>
      <br>
    </dd>
  </dl>
</div>
 

app/views/comments/_comment_body_smart_phone.html.erb
  <div id="comment_<%= c.id %>" data-role="collapsible" data-collapsed="false" data-content-theme="a"> 
    <h3>
      <div>
        <%= c.tune.title %>
        <span id="reply_count_<%= c.id %>">
        <% if c.replies.count > 0 then %>
          <span class="reply-count label label-info"><%= c.replies.count %></span>
        <% else %>
          <span class="reply-count label label-inverse"><%= c.replies.count %></span>
        <% end %>
        </span>
      </div>
      <span class="comment-date">
        <%= c.created_at.strftime("%y/%m/%d %H:%M") %>
      </span>
      <span class="comment-name">
        <%= c.user.name %>
      </span>
      <span id="reply_date_<%= c.id %>">
      <% if c.replies.count > 0 then %>
        <span class="reply-date"><%= c.updated_at.strftime("%m/%d") %></span>
      <% end %>
      </span>
 
    </h3>
    <span><%= mini_last_played_at(c.tune.progress_updated_at(c.user)) %></span>
    <span class="progress-bar"><%= c.tune.progress_val(c.user) %></span>
    <div>
      <a class="same-tuning-btn" href="#tune_list" data-tuning="<%= c.tune.tuning.id %>" data-inline="true" >
        <span class="tuning-name">
          <%= c.tune.tuning.name %>
          <% if c.tune.tuning.capo != nil and c.tune.tuning.capo != 0 %>
            <span> Capo : <%= c.tune.tuning.capo =%></span>
          <% end %>
        </span>
      </a>
    </div>
    <div class="progress-word" style="word-break:break-all;">
      <%= auto_link( simple_format(c.text),:all, :target => "_blank") %>
    </div>

    <% if current_user %>
      <form method="post" class="add-reply-form form-inline">
        <textarea class="add-reply-form-msg" data-mini="true" maxlength="200" placeholder="Reply"></textarea>
        <a data-role="button" class="add-reply-button" data-id="<%= c.id %>" data-mini="true" data-inline="true">Send</a>
      </form>
    <% end %>

    <div id="comment_reply_<%= c.id %>">
      <% c.replies.order("updated_at DESC").each do |r| %>
        <div id="reply_<%= r.id %>" class="comment-one">
          <div>
            <span class="comment-date">
              <%= r.created_at.strftime("%Y/%m/%d %H:%M") %>
            </span>
            <span class="comment-name">
              <%= r.user.name %>
            </span>
            <% if r.user == current_user %>
            <span class="remove-reply">
              <a href="#remove_reply_dialog" data-rel="dialog" data-transition="pop" class="remove-reply-button" data-id="<%= r.id %>" data-comment-id="<%= c.id %>" data-mini="true" data-inline="true">x</a>
            </span>
          <% end %>
          </div>
          <div class="comment-text" style="word-break:break-all;">
            <%= auto_link( simple_format(r.text),:all, :target => "_blank") %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/comments/_comment_list_smart_phone.html.erb
<% @comments.each do |c| %>
  <div id="comment_<%= c.id %>" data-role="collapsible" data-content-theme="a"> 
    <h3>
      <div>
        <%= c.tune.title %>
        <span id="reply_count_<%= c.id %>">
        <% if c.replies.count > 0 then %>
          <span class="reply-count label label-info"><%= c.replies.count %></span>
        <% else %>
          <span class="reply-count label label-inverse"><%= c.replies.count %></span>
        <% end %>
        </span>
      </div>
      <span class="comment-date">
        <%= c.created_at.strftime("%y/%m/%d %H:%M") %>
      </span>
      <span class="comment-name">
        <%= c.user.name %>
      </span>
      <span id="reply_date_<%= c.id %>">
      <% if c.replies.count > 0 then %>
        <span class="reply-date"><%= c.updated_at.strftime("%m/%d") %></span>
      <% end %>
      </span>
 
    </h3>
    <span><%= mini_last_played_at(c.tune.progress_updated_at(c.user)) %></span>
    <span class="progress-bar"><%= c.tune.progress_val(c.user) %></span>
    <div>
      <a class="same-tuning-btn" href="#tune_list" data-tuning="<%= c.tune.tuning.id %>" data-inline="true" >
        <span class="tuning-name">
          <%= c.tune.tuning.name %>
          <% if c.tune.tuning.capo != nil and c.tune.tuning.capo != 0 %>
            <span> Capo : <%= c.tune.tuning.capo =%></span>
          <% end %>
        </span>
      </a>
    </div>
    <div class="progress-word">
      <%= auto_link( simple_format(c.text),:all, :target => "_blank") %>
    </div>

    <% if current_user %>
      <form method="post" class="add-reply-form form-inline">
        <textarea class="add-reply-form-msg" data-mini="true" maxlength="200" placeholder="Reply"></textarea>
        <a data-role="button" class="add-reply-button" data-id="<%= c.id %>" data-mini="true" data-inline="true">Send</a>
      </form>
    <% end %>

    <div id="comment_reply_<%= c.id %>">
      <% c.replies.order("updated_at DESC").each do |r| %>
        <div id="reply_<%= r.id %>" class="comment-one">
          <div>
            <span class="comment-date">
              <%= r.created_at.strftime("%Y/%m/%d %H:%M") %>
            </span>
            <span class="comment-name">
              <%= r.user.name %>
            </span>
            <% if r.user == current_user %>
            <span class="remove-reply">
              <a href="#remove_reply_dialog" data-rel="dialog" data-transition="pop" class="remove-reply-button" data-id="<%= r.id %>" data-comment-id="<%= c.id %>" data-mini="true" data-inline="true">x</a>
            </span>
          <% end %>
          </div>
          <div class="comment-text" style="word-break:break-all;">
            <%= auto_link( simple_format(r.text),:all, :target => "_blank") %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/comments/_comment_with_tune_name.html.erb
<div id="comment_<%= c.id %>">
  <dl>
    <dt>
      <%= link_to c.created_at.strftime("%Y/%m/%d %H:%M"), comment_path(c.id) %>
      <div style="float: right">
        <%= link_to reply_count_label(c), comment_path(c.id) %>
      </div>
    </dt>
    <dd>
      <span><%= link_to c.tune.title, user_tune_path(c.user,c.tune) %></span>
      <div class="comment-text" style="word-break:break-all;"><%= vrp_player_only_link(auto_link( simple_format(c.text))) %></div>
      <div class="comment-name">
        by <%= link_to c.user.default_name, user_tunes_path(c.user) %>
        <%= icon_img(c.user) %>
      </div>
      <br>
    </dd>
  </dl>
</div>

app/views/comments/_header_smart_phone.html.erb
<div data-role="header" data-position="fixed">
  <h3>コタれん</h3>

  <% if current_user %>
    <%= link_to 'Home', user_tunes_path(current_user), :class => 'ui-btn-left'  %>
    <%= link_to 'Logout', destroy_user_session_path , :method => :get, :class => 'ui-btn-right' %>
  <% else %>
    <%= link_to 'Login', new_user_session_path, :class => 'ui-btn-right'  %>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#my_comment_text_area').val("");
var $comment = $('<div/>').html("<%= raw @comment_html %>");
$comment.hide();
$('#my_comments').prepend($comment);
$comment.fadeIn();

app/views/comments/destroy.js.erb
$('#comment_<%= @comment_id %>').fadeOut();

app/views/comments/show.html.erb
<div class="container">
  <div class="row">
    <div class="span6">
      <div id="content" class="ui-widget ui-widget-content ui-corner-all">
        <div id="comments">
          <div id="my_comments">
            <% c = @comment %>
            <dl>
              <dt>
                <%= c.created_at.strftime("%Y/%m/%d %H:%M") %> <span><%= link_to c.tune.title, user_tune_path(c.user,c.tune) %></span>
                <div class="comment-name">
                  <%= link_to c.user.default_name, user_tunes_path(c.user) %>
                  <%= icon_img(c.user) %>
                </div>
              </dt>
              <dd>
                <div class="comment-text" style="word-break:break-all;"><%= auto_link( simple_format(c.text)) %></div>
              </dd>
            </dl>
          </div>
          <% if current_user %>
          <form method="post" class="add-reply-form">
            <textarea class="add-reply-form-msg"  maxlength="200" placeholder="<%= c.user.default_name %>さんの練習記録にコメントしよう！"></textarea>
            <a class="btn add-reply-button" data-id="<%= c.id %>"><i class="icon-pencil"></i> コメントする</a>
          </form>
          <% end %>
        </div>
      </div>
    </div>
    <div class="span6">
      <div id="content" class="ui-widget ui-widget-content ui-corner-all">
        <div id="replies">
        <% c.replies.order("updated_at DESC").each do |r| %>
          <%= render :partial => "replies/reply_body", :locals => { :c => c, :r => r } %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    showComment();
    applyYoutubin("#my_comments .comment-text a");
    applyYoutubin("#replies .comment-text a");
    $(".add-reply-form-msg").autofit({min_height: 70});
  });
</script>

app/views/comments/show_smart_phone.html.erb
<script>
var CurrentUserID = <%= current_user ? current_user.id : -1  %>;
var CommentID = <%= @comment.id %>;
</script>


<ons-navigator></ons-navigator>

<ons-template id="detailsComment.html">
  <!-- ko if: item() == null -->
  <ons-page>
    <ons-toolbar>
      <div class="center">Loading ...</div>
    </ons-toolbar>
    <div class="progress-bar progress-bar--indeterminate">
      <div class="progress-bar__primary"></div>
      <div class="progress-bar__secondary"></div>
    </div>
  </ons-page>
  <!-- /ko -->

  <!-- ko if: item() != null -->
  <ons-page>
    <ons-toolbar>
      <div class="left">
        <ons-toolbar-button data-bind="click: go_to_home">
          <ons-icon icon="md-home"></ons-icon>
        </ons-toolbar-button>
      </div>

      <div class="center" data-bind="text: item().tune.title"></div>
    </ons-toolbar>

    <ons-row style="padding: 10px 10px 0px 10px">
      <span class="list__item__title">
        <span style="word-break:break-all" data-bind="commentHtml: item().comment.text"></span>
      </span>
      <span class="list__item__subtitle">
        <span data-bind="text: date_format(item().comment.created_at())"></span>
        <span style="float: right; margin: 0 5px 0 0 " data-bind="text: item().user.name"></span>
      </span>
    </ons-row>

    <% if current_user %>
      <ons-row style="padding: 10px 5px 0px 5px">
        <textarea class="textarea" data-bind="textInput: inputReply" style="width:100%;height:50px;margin-top:4px;" placeholder="リプライ"></textarea>
      </ons-row>
      <ons-row style="padding: 5px 5px 0px 5px">
        <ons-col style="margin: 5px">
          <ons-button modifier="large" data-bind="click: save_reply">リプライ</ons-button>
        </ons-col>
        <ons-col style="margin: 5px"></ons-col>
        <ons-col style="margin: 5px"></ons-col>
        <ons-col style="margin: 5px">
          <ons-button modifier="large--quiet" data-bind="visible: isShowDelete, click: delete_comment">削除</ons-button>
        </ons-col>
      </ons-row>
    <% end %>

    <ons-list modifier="inset" style="margin: 5px" data-bind="foreach: item().replies">
      <ons-list-item modifier="longdivider">
        <div class="center">
          <span class="list__item__title">
            <span style="word-break:break-all" data-bind="commentHtml: text"></span>
          </span>
          <span class="list__item__subtitle">
            <span data-bind="text: $parent.date_format(updated_at())"></span>
            <span style="float: right; margin: 0 5px 0 0 " data-bind="text: user.name"></span>
          </span>
        </div>
      </ons-list-item>
    </ons-list>
  </ons-page>
  <!-- /ko -->
</ons-template>

<%= javascript_include_tag "comments_smart_phone" %>