config/routes.rb
gem 'grape'

Rails.application.routes.draw do
  mount Api::TunesApi => '/api'

  get "albums/index"

  get "ranking/index"
  get "ranking/latest_played"

  root :to => "welcome#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'users', :to => 'users#index', :as => :user_root

  resources :users do
    get :list , :on => :collection
    resources :tunes do
      resources :comments
      resources :progresses
      get :all , :on => :collection
      post :get_tunes_list , :on => :collection
      post :update_progress , :on => :collection
      get :load_tune_list, :on => :collection
      get :load_tune, :on => :collection
    end

    resources :albums do
      get :load_album_list, :on => :collection
    end

    resources :tunings do
      get :load_tuning_list, :on => :collection
    end
  end


  resources :comments do
    get :load_comment_list, :on => :collection
    resources :replies, :only => %w[create destroy]
  end

  resources :recordings
end

app/models/tune.rb
class Tune < ActiveRecord::Base
  def self.all_or_filter_by_tuning(tuning)
    return self.order("tunes.id ASC") if Tuning.find_by_name(tuning) == nil
    self.includes(:tuning).where("tunings.name = ?", tuning).references(:tuning).order("tunes.id ASC")
  end

  def self.all_or_filter_by_tuning_id(tuning_id)
    return self.order("tunes.id ASC") if Tuning.find_by_id(tuning_id) == nil
    self.includes(:tuning).where("tunings.id = ?", tuning_id).references(:tuning).order("tunes.id ASC")
  end

  def self.get_tune_ranking
    self
      .left_outer_joins(:progresses)
      .group(:id)
      .select('tunes.*, COUNT(progresses.percent > 0) AS active_count')
      .order('active_count DESC')
  end

  def self.all_play_history(user)
    touched_tunes = self.play_history.progress_by_user(user)
    untouched_tunes = self.order("id ASC") - touched_tunes
    touched_tunes + untouched_tunes
  end

  belongs_to :tuning
  has_many :recordings
  has_many :comments
  has_many :progresses

  scope :doing, lambda {
    includes(:progresses).where("progresses.percent > 0 and progresses.percent < 100").references(:progresses).order("tunes.id ASC")
  }
  scope :done, lambda {
    includes(:progresses).where("progresses.percent = 100").references(:progresses).order("tunes.id ASC")
  }
  scope :touched, lambda {
    includes(:progresses).where("progresses.percent > 0").references(:progresses).order("tunes.id ASC")
  }
  scope :play_history, lambda {
    includes(:progresses).where("progresses.percent > 0").references(:progresses).order("progresses.updated_at DESC")
  }
  scope :progress_by_user, lambda {|user|
    includes(:progresses).where("progresses.user_id = ?", user.id).references(:progresses).order("tunes.id ASC")
  }
  scope :by_status_and_user, lambda {|status, user|
    case status
    when "doing"
      doing.progress_by_user(user)
    when "done"
      done.progress_by_user(user)
    when "touched"
      touched.progress_by_user(user)
    when "play_history"
      play_history.progress_by_user(user)
    end
  }

  def progress_val_and_updated_at(user)
    progress = self.active_progress_by_user(user)
    {
      val: progress.try!(:percent) || 0,
      updated_at: progress.try!(:updated_at ) || "-"
    }
  end

  def progress_val(user)
    progress = self.progresses.by_user(user).first
    progress.try!(:percent) || 0
  end

  def progress_updated_at(user)
    progress = self.active_progress_by_user(user)
    progress.try!(:updated_at) || "-"
  end

  def progress_created_at(user)
    progress = self.active_progress_by_user(user)
    progress.try!(:created_at) || "-"
  end

  def active_progress_by_user(user)
    self.progresses.by_user(user).active.first
  end

  def update_progress(user, val)
    raise ArgumentError if !user

    progress = self.progresses.find_or_initialize_by(user_id: user.id)
    #TODO: どんな値でも updated_at を更新したいので一旦 0 で保存している
    #      もっと良い方法があれば変更する。
    progress.percent = 0
    progress.save!
    progress.percent = val
    progress.save!
  end

  def touched_progresses
    #self.progresses.active.order_by_progress_degrees
    self.progresses.active.map{|pr| [pr, pr.user.comments.by_tune(self).count]}.sort{|a,b| b[1] <=> a[1] }
  end

end

app/controllers/tunes_controller.rb
class TunesController < ApplicationController

  @@statuses_def = [
      ['All Status', 'all_status'],
      ['Touched'   , 'touched'],
      ['Trying'     , 'doing'],
      ['Completed'  , 'done'],
      ['PlayHistory','play_history'],
  ]

  def index
    @user = User.find(params[:user_id])
    if request.smart_phone?
      @tunes = Tune.all_play_history(@user)
      @other_comment = Comment.other_by(@user,30).sample
    else
      @albums = Album.order("id ASC")
      @statuses = @@statuses_def

      @current_album = selected_album_title
      @current_tuning = selected_tuning_name
      @current_status = selected_status

      @latest_comments = @user.comments.latest.order("updated_at DESC")
      @other_comments = Comment.other_by(@user).order("updated_at DESC")

      @tunes = Tune.preload(:tuning)

      set_tune_counts(@user)
    end
  end

  def show
    @user = User.find(params[:user_id])
    @tune = Tune.find(params[:id])
    @progress_val = @tune.progress_val(@user)
    @comment = Comment.new
    @comments = @user.comments.by_tune(@tune)
    @other_comments = Comment.other_by(@user).by_tune(@tune)
  end

  #TODO: 未使用かも
  def all
    @albums = Album.order("id ASC")
  end

  def get_tunes_list
    @user = User.find(params[:user_id])
    album = Album.find_by_title(params[:album_title])
    tuning = params[:tuning_name]
    status = params[:tune_status]

    set_current_tune_statuses_to_session( album,tuning,status)

    base_tunes = album ? album.tunes : Tune
    @tunes = base_tunes.by_status_and_user(selected_status[1],@user).all_or_filter_by_tuning(tuning)

    set_tune_counts(@user)

    render :json => { tunes: @tunes.map{|t| {:id => t.id} },
                      touched_count: @touched_count,
                      doing_count: @doing_count,
                      done_count: @done_count}
  end

  def update_progress
    @user = current_user
    @tune = Tune.find(params[:tune_id])
    @tune.update_progress(@user,params[:progress_val])
    set_tune_counts(@user)
    @user.add_activity

    if request.smart_phone?
      render :json => {
          id:  @tune.id,
          date: @tune.progress_updated_at(@user)
        }
    end
  end

  def load_tune_list
    @user = User.find(params[:user_id])
    @tunes = Tune.all_play_history(@user)

    lists = render_to_string :partial => 'tune_list_body_smart_phone'
    render :json => { lists: lists },
           :callback => 'showTuneList'
  end

  def load_tune
    @user = User.find(params[:user_id])
    @tune = Tune.find(params[:tune_id])

    body = render_to_string :partial => 'tune_body_smart_phone'
    progre_controller = render_to_string :partial => 'tune_controller_smart_phone'
    render :json => { id: @tune.id,
                      user_id: @user.id,
                      tune: body,
                      controller: progre_controller
                    },
           :callback => 'showTune'
  end

  private
  def set_current_tune_statuses_to_session( album, tuning, status )
    session[:current_album_id] = album.try(:id)
    session[:current_tuning_id] = Tuning.find_by_name(tuning).try(:id)

    status_def = @@statuses_def.detect{|sd| sd[0] == status }
    session[:current_status] = status_def ? status_def : @@statuses_def[0]
  end

  def selected_album_title
    session[:current_album_id] ? Album.find(session[:current_album_id]).title : "All Albums"
  end

  def selected_tuning_name
    session[:current_tuning_id] ? Tuning.find(session[:current_tuning_id]).name : "All Tunings"
  end

  def selected_status
    session[:current_status] ? session[:current_status] : @@statuses_def[0]
  end

  def set_tune_counts(user)
    @base_tunes = session[:current_album_id] ? Album.find(session[:current_album_id]).tunes : Tune
    tuning = session[:current_tuning_id] ? Tuning.find(session[:current_tuning_id]).name : ""

    @touched_count = @base_tunes.by_status_and_user(@@statuses_def[1][1],user).all_or_filter_by_tuning(tuning).count
    @doing_count   = @base_tunes.by_status_and_user(@@statuses_def[2][1],user).all_or_filter_by_tuning(tuning).count
    @done_count    = @base_tunes.by_status_and_user(@@statuses_def[3][1],user).all_or_filter_by_tuning(tuning).count
  end

end

app/helpers/tunes_helper.rb
module TunesHelper
end

app/views/tunes/_album_list_body_smart_phone_iphone.html.erb
    <% @albums.each do |a| %>
      <li id="album_id_<%= a.id %>">
        <a href="#tune_list" data-id="<%= a.id %>" data-transition="slidefade">
          <img src="/assets/albums/mini/<%= a.title %>_s.jpg" class="album-img">
          <h3 class="tune-title"><%= a.title %></h3>
          <p><%= a.tunes.count %> tunes.</p>
          <p><span id="album_progress_<%= a.id %>" class="progress-bar"><%= a.progress_average(@user) %></span></p>
        </a>
      </li>
    <% end %>

app/views/tunes/_comments_smart_phone.html.erb
<div class="comment-area">
<% user.comments.by_tune(tune).each do |c| %>
  <div id="comment_<%= c.id %>" class="comment-one">
    <div class="comment-date"><%= c.created_at.strftime("%Y/%m/%d %H:%M") %></div>
    <div class="comment-text" style="word-break:break-all;">
      <%= auto_link( simple_format(c.text),:all, :target => "_blank") %>
    </div>
  </div>
<% end %>
</div> 

app/views/tunes/_header_smart_phone_iphone.html.erb
<div data-role="header" data-position="fixed">
  <!-- //TODO: 作成中
  <% if current_user == @user %>
    <% if @user.icon_url.blank? == false %>
      <a href="#option" class="ui-btn-left"><%= image_tag(@user.icon_url, :height => "16" ) %> Option</a>
    <% else %>
      <a href="#option" data-icon="gear" class="ui-btn-left">Option</a>
    <% end %>
  <% end %>
  -->
 
  <% case state %>
  <% when 'tune_list' %>
    <h3>コタれん</h3>
  <% when 'album_list' %>
    <h3>アルバム</h3>
  <% when 'tuning_list' %>
    <h3>チューニング</h3>
  <% when 'tune' %>
    <a data-rel="back" data-icon="back" class="ui-btn-left">戻る</a>
    <h3>曲詳細</h3>
  <% end %>

  <% if current_user %>
    <%= link_to 'Logout', destroy_user_session_path , :method => :get, :class => 'ui-btn-right' %>
  <% else %>
    <%= link_to 'Login', new_user_session_path, :class => 'ui-btn-right'  %>
  <% end %>
</div>

app/views/tunes/_tune_body_smart_phone_iphone.html.erb
  <div data-role="content" data-theme="a">
    <h2><%= @tune.title %></h2>
    <div class="album-title">
      <p>
        <%= raw @tune.recordings.inject([]){|albums,r| albums << r.album.title}.join("<br>") %>
      </p>
      <% @tune.recordings.each do |r| %>
        <a href="#tune_list" data-id="<%= r.album.id %>" data-transition="slidefade" class="tune-album-img" >
          <img src="/assets/albums/mini/<%= r.album.title %>_s.jpg" class="album-img">
        </a>
      <% end %>
    </div> 

    <center>
    <p><a class="same-tuning-btn" href="#tune_list" data-tuning="<%= @tune.tuning.id %>" data-role="button" data-inline="true" >
      <span class="tuning-name">
      <%= @tune.tuning.name %>
      <% if @tune.tuning.capo != nil and @tune.tuning.capo != 0 %>
        <span> Capo : <%= @tune.tuning.capo =%></span>
        <br/>
      <% end %>
      </span>
      (<%= @tune.tuning.tunes.count %> tunes)
    </a></p>

    <span id="progress_updated_at_<%= @tune.id %>">
      <%= last_played_at(@tune.progress_updated_at(@user)) %>
    </span>
    <span id="tune_progress_<%= @tune.id %>" class="progress-bar"><%= @tune.progress_val(@user) %></span>
  </center>

    <% if current_user == @user %>
    <div class="ui-grid-b">
      <div class="ui-block-a">
        <button onclick="progress_controller.down('<%= @user.id %>','<%= @tune.id %>')"><font style="font-size: 14pt;"><%= "<<" %></font></button>
      </div>
      <div class="ui-block-b">
        <button onclick="progress_controller.play('<%= @user.id %>','<%= @tune.id %>')"><i class="icon-music icon-white"></i>+1</font></button>
      </div>
      <div class="ui-block-c">
        <button onclick="progress_controller.up('<%= @user.id %>','<%= @tune.id %>')"><font style="font-size: 14pt;"><%= ">>" %></font></button>
      </div>
    </div>

    <div id="progress_response_<%= @tune.id %>" class="progress-response">
      <div id="progress_word_<%= @tune.id %>" class="progress-word"></div>
      <div id="progress_title_<%= @tune.id %>" class="progress-title"></div>
    </div>

    <form method="post" class="add-comment-form form-inline">
      <textarea class="add-comment-form-msg" data-mini="true" maxlength="200" placeholder="Memo"></textarea>
      <a data-role="button" class="add-comment-button" data-mini="true" data-inline="true">Add</a>
    </form>
    <% end %>

    <%= render "comments_smart_phone_iphone", { :user => @user , :tune => @tune } %>
  </div>

app/views/tunes/_tune_list_body_smart_phone.html.erb
    <% @tunes.each do |t| %>
      <li id="id_<%= t.id %>" class="tune_li <%= t.recordings.inject(""){|album_classes, r| album_classes << "album_#{r.album.id} "} %> <%= "tuning_#{t.tuning.id}" %>" >
        <a href="#tune_<%= t.id %>" data-transition="slidefade">
          <%= image_tag t.recordings[0].album.mini_thumbnail_url, :class => "album-img" %>
          <h3 class="tune-title"><%= t.title %></h3>
          <p>
            <span class="tuning-name"><%= t.tuning.name %>
            <% if t.tuning.capo != nil and t.tuning.capo != 0 %>
              <span> (Capo : <%= t.tuning.capo =%>)</span>
            <% end %>
            </span>
          </p>
          <p>
            <% p = t.progress_val_and_updated_at(@user) %>
            <span id="tune_list_progress_updated_at_<%= t.id %>">
              <%= mini_last_played_at(p[:updated_at]) %>
            </span>
            <span id="progress_<%= t.id %>" class="progress-bar"><%= p[:val] %></span>
          </p>
        </a>
      </li>
    <% end %>

app/views/tunes/_tunes_list_body.html.erb
<div id="tune-list">
<table id="tune_list_table" style="display:none">
  <% @tunes.each do |t| %>
    <tr id="tune_<%= t.id %>" class="tune-tr" style="display:none">
      <td class="tune-title"><%= link_to t.title, user_tune_path(@user,t) %></td>
      <td class="tuning-name"><%= link_to t.tuning.name,"#" %></td>

      <% if current_user == @user %>
        <td class="progress-button">
          <a onclick="progress_controller.down('<%= @user.id %>','<%= t.id %>')"><i class="icon-backward"></i></a>
          <a onclick="progress_controller.play('<%= @user.id %>','<%= t.id %>')"><i class="icon-music"></i></a>
          <a onclick="progress_controller.up('<%= @user.id %>','<%= t.id %>')"><i class="icon-forward"></i></a>
        </td>
      <% else %>
        <td class="progress-button">
        </td>
      <% end %>

      <% p = t.progress_val_and_updated_at(@user) %>
      <td class="progress-bar-area"><span id="progress_<%= t.id %>" class="progress-bar"><%= p[:val] %></span></td>
      <td class="progress-date" id="progress_updated_at_<%= t.id %>"><%= last_played_at( p[:updated_at] ) %></td>
 
   </tr>
  <% end %>
</table>
</div>

<script>
  $('.tuning-name a').click(
    function(){
      var tuning = $(this).html();
      $('#tuning_name').val(tuning)
      loadTunes();
    }
  );

  $(".progress-bar").each(function(elem){
    $(this).progressBar(progress_default_option);
  });

  updateElem('#display_num', <%= @tunes.count %>)

  updateElem('#touched_num',<%= @touched_count %>)
  updateElem('#doing_num',<%= @doing_count %>)
  updateElem('#done_num',<%= @done_count %>)
</script>

app/views/tunes/all.html.erb
<% @albums.each do |alb| %>
  <h2><%= alb.title %></h2>
  <table>
    <% alb.recordings.each do |rec| %>
      <tr><td><%= rec.tune.title %></td><td><%= rec.tune.tuning.name %></td></tr>
    <% end %>
  </table>
<% end %>

app/views/tunes/index.html.erb
<div class="container">
  <%= render "layouts/title" %>
  <div class="row">
    <div class="span3">
      <div id="menu-tabs">
        <div class="out-of-tabs">
          <center>
            <ul class="tune-counts">
              <li>
              <strong id="display_num" class="tune_s_num" >0</strong>
              <span>All Tunes</span>
              </li>
              <li>
              <strong id="touched_num" class="tune_s_num" >0</strong>
              <span>Touched</span>
              </li>
              <li>
              <strong id="doing_num" class="tune_s_num" >0</strong>
              <span>Trying</span>
              </li>
              <li>
              <strong id="done_num" class="tune_s_num" >0</strong>
              <span>Completed</span>
              </li>
            </ul>
            <br>

            <div class="album-list">
              <a href="#" data-name="All Albums">
                <%= image_tag "albums/mini/ALL.png", :class => "album-img", :alt => "All Albums", :title => "All Albums" %>
              </a>
              <% Album.all.each do |a| %>
                <a href="#" data-name="<%= a.title %>">
                  <%= image_tag a.mini_thumbnail_url, :class => "album-img", :alt => a.title, :title => a.title %>
                </a>
              <% end %>
            </div>
            <!--
            <%= link_to 'Owner\'s Albums page', user_albums_path(@user) %>
            -->
          </center>
        </div>
      </div>

      <div id="comments-tabs">
        <div id="comments">
          <div class="out-of-tabs">
            <div id="comments-header">
              Practice Records
            </div>
          </div>
          <ul>
            <li><a id="my_comment" href="#my_comments" class="blue0">Owner</a></li>
            <li><a id="other_comment" href="#other_comments" class="blue1">Other</a></li>
          </ul>

          <div id="my_comments">
            <% @latest_comments.each do |c| %>
              <%= render :partial => "comments/comment_with_tune_name", :locals => { :c => c } %>
            <% end %>
          </div>

          <div id="other_comments">
            <% @other_comments.each do |c| %>
              <%= render :partial => "comments/comment_with_tune_name", :locals => { :c => c } %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="span7">
      <div id="tune-tabs">
        <div style="display: none">
          <%= form_tag( get_tunes_list_user_tunes_path(@user), :id => "tunes_list_form", :remote => true, :style => "margin-bottom: 0px;" ) do %>
          <%= select_tag('album_title', options_for_select(["All Albums"] + @albums.map(&:title), @current_album ) , :onchange => "loadTunes();", :class => "span4", :style => "margin-bottom: 2px;" ) %>
          <%= select_tag('tuning_name', options_for_select(["All Tunings"] + Tuning.all.map(&:name).uniq.sort, @current_tuning) , :onchange => "loadTunes();", :class => "span3", :style => "margin-bottom: 2px;" ) %>
          <%= select_tag('tune_status', options_for_select(@statuses.map{|s| s[0]}, @current_status[0] ) , :onchange => "loadTunes();", :style => "display: none") %>
          <%= submit_tag('Update', :id => "update_tunes", :style => "display: none") %>
        <% end %>
        </div>

        <div id="tune-list-header">
          <span>Album: <span id="album_label"><%= @current_album %></span></span>
          <span style="float: right;">Tuning: <span id="tuning_label"><%= @current_tuning %></span></span>
        </div>
        <ul>
          <% @statuses.each_with_index do |s,i| %>
            <li><a id="<%= s[1] %>" href="#tune-list" class="blue<%= i %>"><%= s[0] %></a></li>
          <% end %>
        </ul>

        <div id="tune-list">
          <%= render :partial => "tunes_list_body" %>
        </div>
        <center>
          <div id="loading">
            <%= image_tag 'ajax-loader_kotaren.gif' %>
          </div>
       </center>
      </div>
    </div>

    <div class="span2">
      <div id="tuning-menu" class="ui-widget ui-widget-content ui-corner-all">
        <div class="out-of-tabs">
          <div id="tuning-header">
            <span>Select Tuning</span>
          </div>
          <ul class="nav nav-list tuning-list">
            <li><a href="#">All Tunings</a></li>
            <li><a href="#">Standard</a></li>
            <% Tuning.all.map(&:name).uniq.sort.each do |tuning_name| %>
              <li><a href="#"><%= tuning_name %></a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

  </div>
</div>

<script>
  $(function($){
    $('#tune-tabs').tabs();
    $('#tune-tabs ul li a').click(
      function(){
        var status = $(this).html();
        $('#tune_status').val(status)
        loadTunes();
      }
    );

    $('#menu-tabs').tabs();

    $('#comments-tabs').tabs();
    $('#comments-tabs ul li a').click(
      function(){
        var comments_id = $(this).attr("id") + "s";

        $("#my_comments").hide();
        $("#other_comments").hide();
        $("#" + comments_id).fadeIn();
      }
    );

    $("#<%= @current_status[1] %>").click();
 
    $("#my_comment").click();

    applyYoutubin("#my_comments .comment-text a");
    applyYoutubin("#other_comments .comment-text a");

    $('.album-list').delegate('a', 'click', function(){
      var album = $(this).data('name');
      $('#album_title').val(album)
      $('#album_label').html(album)
      loadTunes();
    }
    );

    $('.tuning-list').delegate('a', 'click', function(){
      var tuning = $(this).html();
      $('#tuning_name').val(tuning)
      $('#tuning_label').html(tuning)
      loadTunes();
    });
  });

</script>

app/views/tunes/show.html.erb
<div class="container">
  <%= render "layouts/title" %>

  <div class="row">
    <div class="span3">
      <div id="detail">
        <div id="detail-tabs">
          <div class="out-of-tabs">
            <center>
              <h2><%= @tune.title %></h2>
              <div class="album-title">
                <% count = @tune.recordings.count %>
                <% @tune.recordings.each do |r| %>
                  <a href="<%= user_albums_path(@user) %>#album_<%= r.album.id %>">
                    <% if count == 1 %>
                      <%= image_tag r.album.thumbnail_url, :class => "album-img album-img-large" %>
                    <% else %>
                      <%= image_tag r.album.mini_thumbnail_url, :class => "album-img" %>
                    <% end %>
                  </a>
                <% end %>
                <div>
                  <% @tune.recordings.each do |r| %>
                    <a href="<%= user_albums_path(@user) %>#album_<%= r.album.id %>" class="tune-album-img">
                      <%= r.album.title %>
                    </a>
                    </br>
                  <% end %>
                </div>
              </div>
              <br>
              <p><span class="tuning"><%= @tune.tuning.name =%></span></p>
              <% if @tune.tuning.capo != nil and @tune.tuning.capo != 0 %>
                <p><span class="tuning">(Capo : <%= @tune.tuning.capo =%>)</span></p>
              <% end %>
              <hr>
              <p>
              <span id="progress_updated_at_<%= @tune.id %>">
                <%= last_played_at(@tune.progress_updated_at(@user)) %>
              </span>
                <span id="progress_<%= @tune.id %>" class="progress-bar"><%= @progress_val %></span>
              </p>
              <% if current_user == @user %>
                <button class="btn btn-inverse" onclick="progress_controller.down('<%= @user.id %>','<%= @tune.id %>')"><font style="font-size: 14pt;"><%= "<<" %></font></button>
                <button class="btn btn-inverse" onclick="progress_controller.play('<%= @user.id %>','<%= @tune.id %>')">+1 <i class="icon-music icon-white"></i></font></button>
                <button class="btn btn-inverse" onclick="progress_controller.up('<%= @user.id %>','<%= @tune.id %>')"><font style="font-size: 14pt;"><%= ">>" %></font></button>
              <% end %>
              <div>
                <%= first_played_at(@tune.progress_created_at(@user)) %>
              </div>

              <hr>
            </center>
          </div>
          <div id="comments">
            <center>
              <div class="out-of-tabs">
                <h3>練習記録</h3>
              </div>
            </center>
            <ul>
              <li><a id="my_comment" href="#my_comments" class="blue0">Owner</a></li>
              <li><a id="other_comment" href="#other_comments" class="blue1">Other (<%= @other_comments.count %>)</a></li>
            </ul>

              <% if @user == current_user %>
                <form method="post" class="add-comment-form">
                  <textarea class="add-comment-form-msg"  maxlength="199" placeholder="今日の練習はどうでしたか？(YoutubeのURLを貼るといいかも)"></textarea>
                  <a class="btn add-comment-button" data-url="<%= user_tune_comments_path(@user,@tune,@comment) %>"><i class="icon-pencil"></i>記録する</a>
                </form>
              <% end %>
            <div id="my_comments">
              <% @comments.each do |c| %>
                <%= render "comments/comment_body", {:c => c } %>
              <% end %>
            </div>

            <div id="other_comments">
              <% @other_comments.each do |c| %>
                <%= render "comments/comment_body", {:c => c } %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="span7">
      <div id="sub-contents">
        <ul>
          <li><a id="ref-video" href="#ref-videos" class="blue0">関連動画(Youtube)</a></li>
        </ul>
        <div id="ref-videos"></div>
      </div>
    </div>

    <div class="span2">
      <div id="tune-players" class="ui-widget ui-widget-content ui-corner-all">
        <div class="out-of-tabs">
          <div id="players-header">
            <span>Players</span>
          </div>
          <ul class="nav nav-list tuning-list">
            <% @tune.touched_progresses.each do |p| %>
              <% pr = p[0] %>
              <li>
                <table width="100%">
                  <tr>
                    <td class="user-icon-mini">
                      <% if pr.user.icon_url.blank? == false %>
                        <%= image_tag(pr.user.icon_url, :class => "user-icon-img-mini") %>
                      <% end %>
                    </td>
                    <td><%= link_to pr.user.default_name, user_tune_path(pr.user, @tune) %></td>
                    <td align="right">
                      <% comments_count = p[1] %>
                      <% if comments_count > 0 %>
                        <span class="label label-info"><%= comments_count %></span>
                      <% end %>
                    </td>
                  </tr>
                </table>
              </li>

            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function(){
  $('#detail-tabs').tabs();
  $(".progress-bar").each(function(elem){
    $(this).progressBar(progress_default_option);
  });

  $('#detail-tabs ul li a').click(
    function(){
      var comments_id = $(this).attr("id") + "s";

      $("#my_comments").hide();
      $("#other_comments").hide();
      $("#" + comments_id).fadeIn();
    }
  );

  $("#my_comment").click();
  showCommentOnTune();

  $('#sub-contents').tabs();
  $('#sub-contents ul li a').click(
    function(){
      var comments_id = $(this).attr("id") + "s";

      $("#ref-videos").hide();
      $("#play-users").hide();
      $("#" + comments_id).fadeIn();
    }
  );

  loadYoutube('<%= @tune.title %>');
  applyYoutubin("#my_comments .comment-text a");
  applyYoutubin("#other_comments .comment-text a");

  $('.add-comment-form-msg').autofit({min_height: 70});
  $("#ref-video").click();
});
</script>