config/routes.rb
gem 'grape'

Rails.application.routes.draw do
  mount Api::TunesApi => '/api'

  get "albums/index"

  get "ranking/index"
  get "ranking/latest_played"

  root :to => "welcome#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'users', :to => 'users#index', :as => :user_root

  resources :users do
    get :list , :on => :collection
    resources :tunes do
      resources :comments
      resources :progresses
      get :all , :on => :collection
      post :get_tunes_list , :on => :collection
      post :update_progress , :on => :collection
      get :load_tune_list, :on => :collection
      get :load_tune, :on => :collection
    end

    resources :albums do
      get :load_album_list, :on => :collection
    end

    resources :tunings do
      get :load_tuning_list, :on => :collection
    end
  end


  resources :comments do
    get :load_comment_list, :on => :collection
    resources :replies, :only => %w[create destroy]
  end

  resources :recordings
end

app/views/layouts/_title.html.erb
<div id="user-header" class="row-fluid">
  <div class="span3">
    <div style="float: left;">
      <% if @user.icon_url.blank? == false %>
        <%= image_tag(@user.icon_url, :class => "user-icon-img") %>
      <% end %>
    </div>
    <div class="user-name">
      <%= link_to @user.default_name, user_tunes_path(@user) %>
    </div>
  </div>

  <div class="span7">
    <div class="user-option">
      <div id="heatmap"></div>
    </div>
  </div>

  <div class="span2">
    <div class="user-option">
      <dl>
        <dt>youtube</dt>
        <dd><%= @user.youtube_name.blank? ? "-" : link_to(@user.youtube_name, @user.youtube_url) %></dd>
      </dl>
      <dl>
        <dt>twitter</dt>
        <dd><%= @user.twitter_name.blank? ? "-" : link_to(@user.twitter_name, @user.twitter_url) %></dd>
      </dl>
      <dl>
        <dt>guitar</dt>
        <dd><%= @user.guitar.blank? ? "-" : @user.guitar %></dd>
      </dl>
      <dl>
        <dt>tuning</dt>
        <dd><%= @user.tuning.blank? ? "-" : @user.tuning %></dd>
      </dl>
    </div>
  </div>
</div>

<script>
  $(function($){
    var startDate = new Date();
    startDate.setMonth(startDate.getMonth() - 12);

    var parser = function(data) {
      return eval("(" + data + ")");
    };

    var cal = new CalHeatMap();
    cal.init({
      itemSelector: "#heatmap",
      data: "/api/activities?user_id=<%= @user.id %>&start={{d:start}}&stop={{d:end}}",
      afterLoadData: parser,
      cellSize: 7,
      domain: "month",
      subDomain: "day",
      subDomainDateFormat: "%m/%d %Y",
      range: 13,
      tooltip: true,
      start: startDate,
      domainLabelFormat: "%b",
      itemName: ["activity", "activities"],
      legend: [1,3,7,10],
      displayLegend: false
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="apple-mobile-web-app-capable" content="yes"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

  <title>コタれん</title>
  <%= stylesheet_link_tag    "https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/pepper-grinder/jquery-ui.css" %>
  <%= stylesheet_link_tag    "https://cdn.jsdelivr.net/cal-heatmap/3.3.10/cal-heatmap.css" %>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js" %>
  <%= javascript_include_tag "https://d3js.org/d3.v3.min.js" %>
  <%= javascript_include_tag "https://cdn.jsdelivr.net/cal-heatmap/3.3.10/cal-heatmap.min.js" %>

  <%= csrf_meta_tags %>

<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30509611-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
</head>
<body style="padding-top: 60px;">
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/ja_JP/all.js#xfbml=1&appId=406190552742799";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>

  <header>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="brand" href="/">コタれん</a>
          <div class="nav-collapse">
            <% if current_user %>
              <ul class="nav pull-left">
                <li><%= link_to raw('<i class="icon-home"></i>'), user_tunes_path(current_user), :class => 'home' %>
                <li><%= link_to raw('<i class="icon-th"></i>'), user_albums_path(current_user), :class => 'albums' %>
              </ul>
              <ul class="nav pull-right">
                <li><%= link_to 'Activity', ranking_latest_played_path %>
                <li><%= link_to 'Ranking', ranking_index_path %>
                <li><%= link_to 'AllUsers', list_users_path %>
                <% unless current_user.is_sample? %>
                  <li><%= link_to 'EditProfile', edit_user_path(current_user) %>
                <% end %>
                <li><%= link_to 'Logout', destroy_user_session_path , :method => :get %>
              </ul>
            <% else %>
              <ul class="nav pull-right">
                <li><%= link_to 'Activity', ranking_latest_played_path %>
                <li><%= link_to 'Ranking', ranking_index_path %>
                <li><%= link_to 'AllUsers', list_users_path %>
                <li><%= link_to 'Login', new_user_session_path  %>
                <li><%= link_to 'NewAccount', new_user_registration_path %>
              </ul>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </header>

    <%= yield %>

  <footer>
    <span>
    © 2011-2013 Naoki KODAMA. All rights reserved.
    </span>
  </footer>
</body>
</html>

app/views/layouts/application_smart_phone.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="apple-mobile-web-app-capable" content="yes"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta http-equiv='cache-control' content='no-cache'>
  <meta http-equiv='expires' content='0'>
  <meta http-equiv='pragma' content='no-cache'>

  <title>Kotaren</title>
  <%= stylesheet_link_tag "application_smart_phone" %>
  <%= stylesheet_link_tag "https://cdn.jsdelivr.net/cal-heatmap/3.3.10/cal-heatmap.css" %>
  <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/onsen/2.0.4/css/onsenui.min.css" %>
  <%= stylesheet_link_tag "onsen-css-components" %>
  <%= csrf_meta_tags %>

</head>
  <body>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/knockout/3.4.0/knockout-min.js" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/knockout.mapping/2.4.1/knockout.mapping.min.js" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/onsen/2.0.4/js/onsenui.min.js" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.0/moment.min.js" %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.0/locale/ja.js" %>
    <%= javascript_include_tag "application_smart_phone" %>
    <%= javascript_include_tag "knockout_kotaren_custom" %>
    <%= javascript_include_tag "https://d3js.org/d3.v3.min.js" %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/cal-heatmap/3.3.10/cal-heatmap.min.js" %>

    <%= yield %>
  </body>
</html>

app/views/layouts/application_smart_phone_iphone.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="apple-mobile-web-app-capable" content="yes"/>  
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

  <title>Kotaren</title>
  <%= stylesheet_link_tag    "application_smart_phone_iphone" %>

  <%= javascript_include_tag "application_smart_phone_iphone" %>

  <%= csrf_meta_tags %>

</head>
<body style="padding-top: 60px;">
  <%= yield %>
</body>
</html>